name = "portfolio-gelo"
compatibility_date = "2024-04-01"

[build]
command = "npm run build"
cwd = "."

[site]
bucket = ".next/static"

[[build.upload]]
type = "directory"
globs = [".next/**"]
fallthrough = false

[env.production]
routes = [
  { pattern = "/_next/static/*", path = "/static/*" }
]

[limits]
memory_mb = 512 