# Configuration for Cloudflare Pages
[build]
  command = "npm run build"
  output_directory = "out"
  node_compatibility_date = "2024-01-01"

[env]
  NEXT_TELEMETRY_DISABLED = "1"

[build.environment]
  NODE_VERSION = "18" 